datasources:
  races:
    name: '../../DATASETS/F1/races.csv'
    base: True
  drivers:
    name: '../../DATASETS/F1/drivers.csv'
    rename: {driverId: DriverID}
    mergeLogic:
      base: driverId
      field: DriverID
  constructors:
    name: '../../DATASETS/F1/constructors.csv'
    rename: {constructorId: ConstructorID}
    mergeLogic:
      base: constructorId
      field: ConstructorID
  circuits:
    name: '../../DATASETS/F1/circuits.csv'
    rename: {circuitId: CircuitID}
    mergeLogic:
      base: circuitId
      field: CircuitID
  qualifying:
    name: '../../DATASETS/F1/qualifying.csv'
    merge_with_base: True
  pitstops:
    name: '../../DATASETS/F1/pit_stops.csv'
    merge_with_base: True
  results:
    name: '../../DATASETS/F1/results.csv'
    merge_with_base: True
  status:
    name: '../../DATASETS/F1/status.csv'
    rename: {statusId: StatusID}
    mergeLogic:
      base: statusId
      field: StatusID

database:
  sqlScript: '../dataF1.sql'
  user: root
  password: admin
  host: localhost
  port: 3306
  name: f1

tables:
  dim_driver:
    DriverID:
      value: driverId
    DriverRef:
      value: driverRef
    DriverNumber:
      value: number
    Code:
      value: code
    Forename:
      value: forename
    Surname:
      value: surname
    DateOfBirth:
      value: dob
    Nationality:
      value: nationality
  
  dim_constructor:
    ConstructorID:
      value: constructorId
    ConstructorRef:
      value: constructorRef
    ConstructorName:
      value: name
    Nationality:
      value: nationality
  
  dim_circuit:
    CircuitID:
      value: circuitId
    CircuitRef:
      value: circuitRef
    CircuitName:
      value: name
    Location:
      value: location
    Country:
      value: country
    Lat:
      value: lat
    Lng:
      value: lng
    Alt:
      value: alt
  
  dim_race:
    RaceID:
      value: raceId
    Year:
      value: year
    Round:
      value: round
    CircuitID:
      fk: dim_circuit
      value: circuitId
    RaceName:
      value: name
    RaceDate:
      value: date
    RaceTime:
      value: time
  
  dim_status:
    StatusID:
      value: statusId
    Status:
      value: status
  
  fact_qualifying:
    QualifyID:
      autogenerated: True
    RaceID:
      fk: dim_race
      value: raceId
    DriverID:
      fk: dim_driver
      value: driverId
    ConstructorID:
      fk: dim_constructor
      value: constructorId
    QualifyNumber:
      value: number
    Position:
      value: position
    Q1:
      value: q1
    Q2:
      value: q2
    Q3:
      value: q3
  
  fact_pitstops:
    PitStopID:
      autogenerated: True
    RaceID:
      fk: dim_race
      value: raceId
    DriverID:
      fk: dim_driver
      value: driverId
    Stop:
      value: stop
    Lap:
      value: lap
    PitStopTime:
      value: time
    Duration:
      value: duration
    Milliseconds:
      value: milliseconds
  
  fact_results:
    ResultID:
      autogenerated: True
    RaceID:
      fk: dim_race
      value: raceId
    DriverID:
      fk: dim_driver
      value: driverId
    ConstructorID:
      fk: dim_constructor
      value: constructorId
    ResultNumber:
      value: number
    Grid:
      value: grid
    Position:
      value: position
    PositionText:
      value: positionText
    PositionOrder:
      value: positionOrder
    Points:
      value: points
    Laps:
      value: laps
    ResultTime:
      value: time
    Milliseconds:
      value: milliseconds
    FastestLap:
      value: fastestLap
    FastestLapRank:
      value: rank
    FastestLapTime:
      value: fastestLapTime
    FastestLapSpeed:
      value: fastestLapSpeed
    StatusID:
      fk: dim_status
      value: statusId

config:
  dim_driver:
    design: dimension
    id: DriverID
    onDuplicate:
      method: ignore
    onNull:
      method: ignore
  
  dim_constructor:
    design: dimension
    id: ConstructorID
    onDuplicate:
      method: ignore
    onNull:
      method: ignore
  
  dim_circuit:
    design: dimension
    id: CircuitID
    onDuplicate:
      method: ignore
    onNull:
      method: ignore
  
  dim_race:
    design: dimension
    id: RaceID
    onDuplicate:
      method: ignore
    onNull:
      method: ignore
  
  dim_status:
    design: dimension
    id: StatusID
    onDuplicate:
      method: ignore
    onNull:
      method: ignore
  
  fact_qualifying:
    design: fact
    id: [RaceID, DriverID, ConstructorID]
    onDuplicate:
      method: ignore
    onNull:
      method: ignore
  
  fact_pitstops:
    design: fact
    id: [RaceID, DriverID, Stop]
    onDuplicate:
      method: ignore
    onNull:
      method: ignore
  
  fact_results:
    design: fact
    id: [RaceID, DriverID]
    onDuplicate:
      method: ignore
    onNull:
      method: ignore
